version: "3.9"

services:
  app:
    image: registry.neko-piranha.ts.net/astral/buzz:frontend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
      labels:
        - "swarm.autoscale=true"
      restart_policy:
        condition: any
    stop_grace_period: 1s
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/')"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "8604:3000"
    networks:
      - buzz

  backend:
    image: registry.neko-piranha.ts.net/astral/buzz:backend
    environment:
      NO_AUTH_CHECK: "true"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
      restart_policy:
        condition: any
      update_config:
        monitor: 5s
        failure_action: rollback
    stop_grace_period: 1s
    networks:
      - buzz

networks:
  buzz:
    driver: overlay
