version: "3.9"

services:
  app:
    image: git.dgnr.us/astral/buzz:frontend
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "4.0"
          memory: 1024M
      restart_policy:
        condition: any
    stop_grace_period: 1s
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/')"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "8093:3000"
    networks:
      - buzz

  backend:
    image: git.dgnr.us/astral/buzz:backend
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
      restart_policy:
        condition: any
    stop_grace_period: 1s
    networks:
      - buzz

networks:
  buzz:
    driver: overlay
