name: Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker info
          env="${{ secrets.ENV_B64 }}"
          length=${#env}
          echo "Length: $length"
          echo "${{ secrets.ENV_B64 }}" | base64 -d > .env
          ls -l .env
      - run: |
          TAG=${{ gitea.sha }}
          docker build \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:frontend \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG \
            .

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker info
          env="${{ secrets.ENV_B64 }}"
          length=${#env}
          echo "Length: $length"
          echo "${{ secrets.ENV_B64 }}" | base64 -d > .env
          ls -l .env
      - run: |
          TAG=${{ gitea.sha }}
          docker build \
            -f backend.dockerfile \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:backend \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:backend-$TAG \
            .

  push:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - run: |
          TAG=${{ gitea.sha }}
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:backend &
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:backend-$TAG &
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:frontend &
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG &
          wait

      - name: Deploy to k3s
        run: |
          TAG=${{ gitea.sha }}

          # DB migration
          kubectl delete job db-migrate -n buzz --ignore-not-found
          kubectl create job db-migrate \
            --image=mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG \
            -n buzz \
            --command -- bun dr push
          kubectl wait --for=condition=complete job/db-migrate -n buzz --timeout=120s

          # Roll app & backend
          kubectl set image deployment/app app=mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG -n buzz
          kubectl set image deployment/backend backend=mts.dgnr.us:5000/${{ gitea.repository }}:backend-$TAG -n buzz
