name: Build and Push Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore .env
        run: |
          docker info
          env="${{ secrets.ENV_B64 }}"
          length=${#env}
          echo "Length: $length"
          echo "${{ secrets.ENV_B64 }}" | base64 -d > .env
          ls -l .env

      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.CI_TOKEN }}" | docker login \
            100.126.211.77:3002 \
            -u ${{ gitea.actor }} \
            --password-stdin

      - name: Build Image
        run: |
          docker build -t 100.126.211.77:3002/${{ gitea.repository }}:latest .

      - name: Push Image
        run: |
          docker push 100.126.211.77:3002/${{ gitea.repository }}:latest
