name: Build and Push Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker info
          env="${{ secrets.ENV_B64 }}"
          length=${#env}
          echo "Length: $length"
          echo "${{ secrets.ENV_B64 }}" | base64 -d > .env
          ls -l .env
      - run: |
          TAG=${{ gitea.sha }}
          docker build \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:frontend \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG \
            .

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker info
          env="${{ secrets.ENV_B64 }}"
          length=${#env}
          echo "Length: $length"
          echo "${{ secrets.ENV_B64 }}" | base64 -d > .env
          ls -l .env
      - run: |
          TAG=${{ gitea.sha }}
          docker build \
            -f backend.dockerfile \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:backend \
            -t mts.dgnr.us:5000/${{ gitea.repository }}:backend-$TAG \
            .

  push:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - run: |
          TAG=${{ gitea.sha }}
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:backend &
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:backend-$TAG &
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:frontend &
          docker push mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG &
          wait

      - name: Deploy to production
        run: |
          TAG=${{ gitea.sha }}

          docker service update \
            --image mts.dgnr.us:5000/${{ gitea.repository }}:frontend-$TAG \
            buzz_app
          docker service update \
            --image mts.dgnr.us:5000/${{ gitea.repository }}:backend-$TAG \
            buzz_backend
