name: Build and Push Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.CI_TOKEN }}" | docker login \
            git.dgnr.us \
            -u ${{ gitea.actor }} \
            --password-stdin

      - name: Build Image
        run: |
          docker build -t git.dgnr.us/${{ gitea.repository }}:latest .

      - name: Push Image
        run: |
          docker push git.dgnr.us/${{ gitea.repository }}:latest
